### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by josefantoni** [dalu93/swift-style-guidelines#1]
Servus Luca! Ive been on two of your presentations provided by STRV, but never open your repository. I was a fool, because this is what I am searching for a long time. But I really did not get why do you prefer this over bottom example. Can u provide better answer?

```
    //Well its empty
    var array: [String] = []
    var str: String = ""
    var int: Int = 0
    
    //this is also empty
    var array = [String]()
    var str = String()
    var int = Int()
```

**Comment by dalu93** [comment]
I don't think there is a correct answer for your question @PanMluvci.
I only think, and this is only my opinion, that we should define the type where it's not implicit from the default value

```swift
var array = []
```

won't be readable at all (an firstly it won't compile). To follow the same rule I follow everywhere, I declare the type explicitly as below

```swift
var intArray: [Int] = []
```

I don't use the other way, for the same reason I do this

```swift
let myIntegerConstant: Int = 1
```

and not 

```swift
let myIntegerConstant = Int(1)
```

**Comment by josefantoni** [comment]
U did not get me
```
    //this is variable Zero
    var int: Int = 0
    
    //this is also variable of zero
    var int = Int()
```
Both you and comopiler knows its Integer
```
    //this is type Double
    let pi: Double = 3.16
    
    //this is also type of Double
    let pi = 3.16
```

Again you and compiler know its Type...so why specify it so much...why border to type so much code? Its because like u said matter of your opinion?

**Comment by dalu93** [comment]
I really like consistency in my classes. In case I need to specify that
```swift
let xPosition = 3.5
```

is a `CGFloat`, I need to explicitly use the type there. (`let xPosition: CGFloat = 3.5`).
Let's say that this rule could be true for almost everything except for `Boolean` values.

Regarding this (`var int = Int()`) I think I replied at it in the previous answer

**Comment by josefantoni** [comment]
Aha ok thanks :-) I am always resetting simple type values to initial values with 
```
var int = 60
var str = "sixty"

int = Int() //0
str = String() //""
```
Don't know really why....maybe its nicer :-P 
Never saw or use it like you did here
`int = Int(7)`
 Anyway I was just curious :-) thanks again for repo.

**Comment by dalu93** [comment]
No problem. Before moving on, take a look at the `Foundation` source code. I've never seen declarations like `str = String()` from Apple anywhere
